language: python

addons:
  apt:
    update: true
    packages:
    - portaudio19-dev

install:
  - pip install -r requirements_test.txt
  - pip install .

before_script:
  - "flake8 src"
  - "flake8 tests"

script:
  - pytest --pyargs synthingie
  - pytest tests
